
from __future__ import annotations

from dataclasses import dataclass
import re

from model_utils import token_set,looks_meta


@dataclass
class Candidate:
    source:str
    content:str
    score:float
    goal:float
    context:float
    evidence:float
    progress:float
    naturalness:float
    brevity:float


class Planner:
    """
    Chooses among already-safe semantic candidates.
    Internal graph serialization is never a candidate.
    """

    def __init__(self,memory,trace=True):
        self.memory=memory
        self.trace=trace

    def score(self,goal,user,content,source,evidence_count,state_hit=False):
        low=content.lower()
        n=len(content.split())

        goal_score=8.0
        if goal.name.startswith("social_"):
            goal_score=9.0
        elif goal.name=="explore_assistant":
            goal_score=9.0 if re.search(r"\b(i'm|i am|i think|i'd|i would)\b",low) else 4.0
        elif goal.name=="request_generation":
            goal_score=9.0 if n>=3 else 2.0
        elif goal.name=="challenge_claim":
            goal_score=9.0 if n>=3 else 3.0

        context=0.0
        if self.memory.topic and self.memory.topic.lower() in token_set(content):
            context+=3.0

        for f in self.memory.facts()[:16]:
            if f["subject"] in token_set(content):
                context+=1.5
            if f["object_text"] in token_set(content):
                context+=1.0

        evidence=(
            12.0 if source=="state" and state_hit else
            8.0 if source=="knowledge" and evidence_count else
            2.0 if source=="participant" else
            1.0
        )

        # Never let generic knowledge outrank a direct state answer.
        if goal.name in {
            "request_information",
            "request_explanation",
            "challenge_claim",
        } and source=="knowledge":
            evidence += 2.0 if evidence_count else -8.0

        progress=2.0 if n>=3 else 0.5
        natural=4.0 if content.endswith((".","!","?")) else 1.0
        if looks_meta(content):
            natural-=8.0

        brief=2.0 if n<=8 else 1.5 if n<=16 else 1.0 if n<=30 else 0.4

        # Goal mismatch penalties.
        if (
            goal.name in {
                "request_information","request_explanation",
                "request_opinion","challenge_claim"
            }
            and content.endswith("?")
        ):
            goal_score-=6.0

        if self.memory.last_assistant:
            prev=token_set(self.memory.last_assistant)
            cur=token_set(content)
            if cur and len(prev&cur)/max(1,len(cur))>0.85:
                context-=5.0

        if token_set(user)==token_set(content):
            goal_score-=8.0

        total=goal_score+context+evidence+progress+natural+brief

        return Candidate(
            source,content,total,
            goal_score,context,evidence,progress,natural,brief
        )

    def choose(
        self,
        goal,
        user,
        state_contents,
        knowledge_contents,
        participant,
    ):
        candidates=[]

        for text in state_contents:
            candidates.append(
                self.score(
                    goal,user,text,"state",
                    len(knowledge_contents),
                    True,
                )
            )

        for text in knowledge_contents:
            # knowledge_contents are already natural-language candidates
            # generated by the surface layer, never raw edge strings.
            candidates.append(
                self.score(
                    goal,user,text,"knowledge",
                    len(knowledge_contents),
                    False,
                )
            )

        if participant:
            assessment=participant.assessment
            candidate=self.score(
                goal,
                user,
                participant.raw,
                "participant",
                len(knowledge_contents),
                bool(state_contents),
            )
            # Goal-contribution is now the decisive prior for participant input.
            if assessment.accepted:
                # For generation, the accepted participant is itself the
                # generated content. For conversation/factual tasks it remains
                # merely advisory.
                if goal.name=="request_generation":
                    candidate.score += max(
                        0.0,
                        assessment.contribution-0.5
                    )*14.0
                else:
                    candidate.score += max(
                        0.0,
                        assessment.contribution-0.5
                    )*10.0
                candidates.append(candidate)

        fallback={
            "social_greeting":"Hello!",
            "social_thanks":"You're welcome!",
            "social_goodbye":"Bye!",
            "social_affection":"That's nice to hear.",
            "explore_assistant":"I'm thinking about our conversation.",
            "request_information":"I'm not sure yet.",
            "request_explanation":"I'm not sure yet.",
            "request_generation":"Sure.",
            "request_action":"Sure. What would you like me to do?",
            "request_opinion":"I'm not sure yet.",
            "challenge_claim":"I'm not certain yet.",
            "continue_conversation":"Tell me more.",
        }.get(goal.name,"I'm not sure yet.")

        candidates.append(
            self.score(
                goal,user,fallback,"fallback",
                len(knowledge_contents),
                bool(state_contents),
            )
        )

        source_priority={
            "state":4,
            "participant":3,
            "knowledge":2,
            "fallback":1,
        }
        candidates.sort(
            key=lambda x:(x.score,source_priority.get(x.source,0)),
            reverse=True,
        )

        if self.trace:
            for i,c in enumerate(candidates,1):
                print(
                    f"  [CANDIDATE {i}] source={c.source} "
                    f"score={c.score:.2f} "
                    f"goal={c.goal:.2f} context={c.context:.2f} "
                    f"evidence={c.evidence:.2f} progress={c.progress:.2f} "
                    f"natural={c.naturalness:.2f} brief={c.brevity:.2f}",
                    flush=True,
                )
                print(f"    {c.content!r}",flush=True)

            margin=(
                candidates[0].score-candidates[1].score
                if len(candidates)>1 else candidates[0].score
            )
            print(
                f"  [PLANNER] winner={candidates[0].source} "
                f"score={candidates[0].score:.2f} margin={margin:.2f}",
                flush=True,
            )

        return candidates[0]
