
/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2020-01-28T22:25:05.019-05:00
  3.24.0.5
  
  Standalone prediction code with sample test data for GBMModel named SearchArg

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://192.168.0.103:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://192.168.0.103:54321/3/Models.java/SearchArg > SearchArg.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m SearchArg.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="SearchArg", algorithm="gbm")
public class SearchArg extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Multinomial; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 1; }
  public int nclasses() { return 4; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_SearchArg.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 4;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* currentStateIn */ SearchArg_ColInfo_0.VALUES,
    /* argumentOut */ SearchArg_ColInfo_1.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {0.14285714285714285,0.14285714285714285,0.14285714285714285,0.5714285714285714};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {0.14285714285714285,0.14285714285714285,0.14285714285714285,0.5714285714285714};

  public SearchArg() { super(NAMES,DOMAINS,"argumentOut"); }
  public String getUUID() { return Long.toString(-2212977391437000618L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    SearchArg_Forest_0.score0(data,preds);
    SearchArg_Forest_1.score0(data,preds);
    SearchArg_Forest_2.score0(data,preds);
    SearchArg_Forest_3.score0(data,preds);
    SearchArg_Forest_4.score0(data,preds);
    SearchArg_Forest_5.score0(data,preds);
    SearchArg_Forest_6.score0(data,preds);
    SearchArg_Forest_7.score0(data,preds);
    SearchArg_Forest_8.score0(data,preds);
    SearchArg_Forest_9.score0(data,preds);
    SearchArg_Forest_10.score0(data,preds);
    SearchArg_Forest_11.score0(data,preds);
    SearchArg_Forest_12.score0(data,preds);
    SearchArg_Forest_13.score0(data,preds);
    SearchArg_Forest_14.score0(data,preds);
    SearchArg_Forest_15.score0(data,preds);
    SearchArg_Forest_16.score0(data,preds);
    SearchArg_Forest_17.score0(data,preds);
    SearchArg_Forest_18.score0(data,preds);
    SearchArg_Forest_19.score0(data,preds);
    SearchArg_Forest_20.score0(data,preds);
    SearchArg_Forest_21.score0(data,preds);
    SearchArg_Forest_22.score0(data,preds);
    SearchArg_Forest_23.score0(data,preds);
    SearchArg_Forest_24.score0(data,preds);
    SearchArg_Forest_25.score0(data,preds);
    SearchArg_Forest_26.score0(data,preds);
    SearchArg_Forest_27.score0(data,preds);
    SearchArg_Forest_28.score0(data,preds);
    SearchArg_Forest_29.score0(data,preds);
    hex.genmodel.GenModel.GBM_rescale(preds);
    preds[0] = hex.genmodel.GenModel.getPrediction(preds, PRIOR_CLASS_DISTRIB, data, 0.5);
    return preds;
  }
}
// The class representing training column names
class NamesHolder_SearchArg implements java.io.Serializable {
  public static final String[] VALUES = new String[1];
  static {
    NamesHolder_SearchArg_0.fill(VALUES);
  }
  static final class NamesHolder_SearchArg_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "currentStateIn";
    }
  }
}
// The class representing column currentStateIn
class SearchArg_ColInfo_0 implements java.io.Serializable {
  public static final String[] VALUES = new String[7];
  static {
    SearchArg_ColInfo_0_0.fill(VALUES);
  }
  static final class SearchArg_ColInfo_0_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "-1";
      sa[1] = "0";
      sa[2] = "1";
      sa[3] = "2";
      sa[4] = "3";
      sa[5] = "4";
      sa[6] = "5";
    }
  }
}
// The class representing column argumentOut
class SearchArg_ColInfo_1 implements java.io.Serializable {
  public static final String[] VALUES = new String[4];
  static {
    SearchArg_ColInfo_1_0.fill(VALUES);
  }
  static final class SearchArg_ColInfo_1_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "[0]";
      sa[1] = "[2]";
      sa[2] = "[3]";
      sa[3] = "[]";
    }
  }
}

class SearchArg_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_0_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_0_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_0_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_0_class_3.score0(fdata);
  }
}
class SearchArg_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.1f : 
        0.3f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_0_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.1f : 
        0.3f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_0_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.1f : 
        0.3f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_0_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.1f : 
        0.3f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_1_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_1_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_1_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_1_class_3.score0(fdata);
  }
}
class SearchArg_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.09647874f : 
        0.22582203f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_1_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.09647874f : 
        0.22582203f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_1_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.09647874f : 
        0.22582203f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_1_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.09647874f : 
        0.22582203f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_2_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_2_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_2_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_2_class_3.score0(fdata);
  }
}
class SearchArg_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.093476705f : 
        0.18426757f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_2_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.093476705f : 
        0.18426757f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_2_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.093476705f : 
        0.18426757f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_2_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.093476705f : 
        0.18426757f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_3_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_3_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_3_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_3_class_3.score0(fdata);
  }
}
class SearchArg_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.090895206f : 
        0.15776913f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_3_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.090895206f : 
        0.15776913f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_3_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.090895206f : 
        0.15776913f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_3_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.090895206f : 
        0.15776913f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_4_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_4_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_4_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_4_class_3.score0(fdata);
  }
}
class SearchArg_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08867156f : 
        0.13954683f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_4_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08867156f : 
        0.13954683f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_4_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08867156f : 
        0.13954683f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_4_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08867156f : 
        0.13954683f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_5_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_5_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_5_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_5_class_3.score0(fdata);
  }
}
class SearchArg_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08675646f : 
        0.12637608f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_5_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08675646f : 
        0.12637608f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_5_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08675646f : 
        0.12637608f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_5_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08675646f : 
        0.12637608f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_6_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_6_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_6_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_6_class_3.score0(fdata);
  }
}
class SearchArg_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08510808f : 
        0.11651439f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_6_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08510808f : 
        0.11651439f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_6_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08510808f : 
        0.11651439f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_6_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08510808f : 
        0.11651439f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_7_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_7_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_7_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_7_class_3.score0(fdata);
  }
}
class SearchArg_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08369009f : 
        0.108934f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_7_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08369009f : 
        0.108934f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_7_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08369009f : 
        0.108934f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_7_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08369009f : 
        0.108934f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_8_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_8_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_8_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_8_class_3.score0(fdata);
  }
}
class SearchArg_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08247085f : 
        0.10298849f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_8_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08247085f : 
        0.10298849f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_8_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08247085f : 
        0.10298849f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_8_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.08247085f : 
        0.10298849f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_9_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_9_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_9_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_9_class_3.score0(fdata);
  }
}
class SearchArg_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.081422806f : 
        0.09825068f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_9_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.081422806f : 
        0.09825068f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_9_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.081422806f : 
        0.09825068f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_9_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.081422806f : 
        0.09825068f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_10 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_10_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_10_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_10_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_10_class_3.score0(fdata);
  }
}
class SearchArg_Tree_10_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.080522075f : 
        0.09442694f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_10_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.080522075f : 
        0.09442694f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_10_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.080522075f : 
        0.09442694f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_10_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.080522075f : 
        0.09442694f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_11 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_11_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_11_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_11_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_11_class_3.score0(fdata);
  }
}
class SearchArg_Tree_11_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.079748f : 
        0.09130891f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_11_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.079748f : 
        0.09130891f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_11_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.079748f : 
        0.09130891f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_11_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.079748f : 
        0.09130891f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_12 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_12_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_12_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_12_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_12_class_3.score0(fdata);
  }
}
class SearchArg_Tree_12_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07908276f : 
        0.088744715f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_12_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07908276f : 
        0.088744715f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_12_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07908276f : 
        0.088744715f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_12_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07908276f : 
        0.088744715f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_13 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_13_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_13_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_13_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_13_class_3.score0(fdata);
  }
}
class SearchArg_Tree_13_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07851103f : 
        0.08662116f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_13_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07851103f : 
        0.08662116f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_13_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07851103f : 
        0.08662116f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_13_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07851103f : 
        0.08662116f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_14 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_14_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_14_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_14_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_14_class_3.score0(fdata);
  }
}
class SearchArg_Tree_14_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07801963f : 
        0.084852204f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_14_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07801963f : 
        0.084852204f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_14_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07801963f : 
        0.084852204f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_14_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07801963f : 
        0.084852204f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_15 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_15_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_15_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_15_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_15_class_3.score0(fdata);
  }
}
class SearchArg_Tree_15_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07759721f : 
        0.083371416f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_15_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07759721f : 
        0.083371416f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_15_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07759721f : 
        0.083371416f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_15_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07759721f : 
        0.083371416f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_16 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_16_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_16_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_16_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_16_class_3.score0(fdata);
  }
}
class SearchArg_Tree_16_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07723406f : 
        0.082126744f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_16_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07723406f : 
        0.082126744f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_16_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07723406f : 
        0.082126744f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_16_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07723406f : 
        0.082126744f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_17 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_17_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_17_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_17_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_17_class_3.score0(fdata);
  }
}
class SearchArg_Tree_17_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07692182f : 
        0.0810769f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_17_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07692182f : 
        0.0810769f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_17_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07692182f : 
        0.0810769f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_17_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07692182f : 
        0.0810769f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_18 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_18_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_18_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_18_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_18_class_3.score0(fdata);
  }
}
class SearchArg_Tree_18_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07665333f : 
        0.080188766f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_18_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07665333f : 
        0.080188766f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_18_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07665333f : 
        0.080188766f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_18_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07665333f : 
        0.080188766f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_19 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_19_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_19_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_19_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_19_class_3.score0(fdata);
  }
}
class SearchArg_Tree_19_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07642244f : 
        0.07943556f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_19_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07642244f : 
        0.07943556f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_19_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07642244f : 
        0.07943556f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_19_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07642244f : 
        0.07943556f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_20 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_20_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_20_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_20_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_20_class_3.score0(fdata);
  }
}
class SearchArg_Tree_20_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07622385f : 
        0.07879542f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_20_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07622385f : 
        0.07879542f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_20_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07622385f : 
        0.07879542f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_20_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07622385f : 
        0.07879542f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_21 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_21_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_21_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_21_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_21_class_3.score0(fdata);
  }
}
class SearchArg_Tree_21_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07605304f : 
        0.07825039f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_21_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07605304f : 
        0.07825039f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_21_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07605304f : 
        0.07825039f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_21_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07605304f : 
        0.07825039f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_22 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_22_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_22_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_22_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_22_class_3.score0(fdata);
  }
}
class SearchArg_Tree_22_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.075906105f : 
        0.077785626f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_22_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.075906105f : 
        0.077785626f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_22_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.075906105f : 
        0.077785626f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_22_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.075906105f : 
        0.077785626f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_23 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_23_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_23_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_23_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_23_class_3.score0(fdata);
  }
}
class SearchArg_Tree_23_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.0757797f : 
        0.07738878f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_23_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.0757797f : 
        0.07738878f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_23_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.0757797f : 
        0.07738878f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_23_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.0757797f : 
        0.07738878f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_24 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_24_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_24_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_24_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_24_class_3.score0(fdata);
  }
}
class SearchArg_Tree_24_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07567096f : 
        0.07704953f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_24_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07567096f : 
        0.07704953f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_24_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07567096f : 
        0.07704953f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_24_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07567096f : 
        0.07704953f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_25 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_25_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_25_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_25_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_25_class_3.score0(fdata);
  }
}
class SearchArg_Tree_25_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07557739f : 
        0.07675926f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_25_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07557739f : 
        0.07675926f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_25_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07557739f : 
        0.07675926f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_25_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07557739f : 
        0.07675926f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_26 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_26_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_26_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_26_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_26_class_3.score0(fdata);
  }
}
class SearchArg_Tree_26_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07549688f : 
        0.07651067f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_26_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07549688f : 
        0.07651067f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_26_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07549688f : 
        0.07651067f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_26_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07549688f : 
        0.07651067f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_27 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_27_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_27_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_27_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_27_class_3.score0(fdata);
  }
}
class SearchArg_Tree_27_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.075427614f : 
        0.07629764f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_27_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.075427614f : 
        0.07629764f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_27_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.075427614f : 
        0.07629764f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_27_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.075427614f : 
        0.07629764f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_28 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_28_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_28_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_28_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_28_class_3.score0(fdata);
  }
}
class SearchArg_Tree_28_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07536801f : 
        0.07611497f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_28_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07536801f : 
        0.07611497f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_28_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07536801f : 
        0.07611497f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_28_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07536801f : 
        0.07611497f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


class SearchArg_Forest_29 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += SearchArg_Tree_29_class_0.score0(fdata);
    preds[2] += SearchArg_Tree_29_class_1.score0(fdata);
    preds[3] += SearchArg_Tree_29_class_2.score0(fdata);
    preds[4] += SearchArg_Tree_29_class_3.score0(fdata);
  }
}
class SearchArg_Tree_29_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07531671f : 
        0.07595824f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
}

class SearchArg_Tree_29_class_1 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07531671f : 
        0.07595824f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {32, 0, 0, 0};
}

class SearchArg_Tree_29_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0 /* currentStateIn */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07531671f : 
        0.07595824f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
}

class SearchArg_Tree_29_class_3 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* currentStateIn */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
        -0.07531671f : 
        0.07595824f);
    return pred;
  } // constant pool size = 11B, number of visited nodes = 1, static init size = 30B
  // {11010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {75, 0, 0, 0};
}


